services:
  - type: web
    name: qrng-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONPATH
        value: ..

  - type: web
    name: qrng-frontend
    env: python
    buildCommand: "cd frontend && pip install -r requirements.txt"
    startCommand: "cd frontend && export BACKEND_URL=https://$RENDER_SERVICE_NAME-qrng-backend.onrender.com && python run.py"
    envVars:
      - key: PORT
        value: 10000